/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package assignment.fancode;

import org.testng.annotations.*;

import assignment.fancode.utils.Constants;
import assignment.fancode.utils.LoggerSingleton;

import static org.testng.Assert.*;

public class AppTest {
    @Test
    public void appHasAGreeting() {
        App classUnderTest = new App();
        LoggerSingleton.logger.info(Constants.whatAreMyConstants());
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
