/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package assignment.fancode;

import org.testng.Assert;
import org.testng.annotations.*;

import assignment.fancode.paths.ToDo;
import assignment.fancode.paths.Users;
import assignment.fancode.utils.Constants;
import assignment.fancode.utils.LoggerSingleton;
import assignment.fancode.utils.Logic;
import io.restassured.response.Response;
import com.fasterxml.jackson.databind.ObjectMapper;

import static org.testng.Assert.*;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Map;

public class AppTest {
    @Test
    public void appHasAGreeting() {

        App classUnderTest = new App();
        // Check
        // LoggerSingleton.logger.info(Constants.whatAreMyConstants());

        // Get the data
        ObjectMapper mapper = new ObjectMapper();
        List<Map<String, Object>> userBody = null;
        List<Map<String, Object>> todoBody = null;
        try {
            Response userResponse = Users.getUsers();
            userBody = mapper.readValue(userResponse.getBody().asString(), List.class);
            LoggerSingleton.logger.info("Got users from api");
            LoggerSingleton.logger.debug(String.format("Got users %s", userBody.toString()));
        } catch (Exception e) {
            LoggerSingleton.logger.error(String.format("Error getting user list %s", e.getMessage()));
        }

        try {
            Response todoResponse = ToDo.getToDos();
            todoBody = mapper.readValue(todoResponse.getBody().asString(), List.class);
            LoggerSingleton.logger.info("Got todos from api");
            LoggerSingleton.logger.debug(String.format("Got todos %s", todoBody.toString()));
        } catch (Exception e) {
            LoggerSingleton.logger.error(String.format("Error getting todo list %s", e.getMessage()));
        }
        Assert.assertNotNull(userBody, "Exiting - Null response from TODO");
        Assert.assertNotNull(todoBody, "Exiting - Null response from USERS");

        // Remove users who don't belong to specified sity
        Logic.filterusersByCities(userBody, new ArrayList<>(Arrays.asList(Constants.cities)));
        LoggerSingleton.logger.info("Filtered by City");

        // Remove users who don't have ToDos
        Logic.filterUsersWithToDos(userBody, todoBody);
        LoggerSingleton.logger.info("Filtered by TODO existence");

        LoggerSingleton.logger.debug(String.format("Users after filering by Todo and City %s", userBody.toString()));

        LoggerSingleton.logger
                .info(String.format("Average tasks done by filtered users: %s", Logic.takeOutAverage(userBody)));

        // Checking for percentage completion
        Logic.filterusersByPercCompletion(userBody, Constants.threshold);
        LoggerSingleton.logger.debug(String.format("Users after filering by percCompletion %s", userBody.toString()));

        LoggerSingleton.logger
                .info(String.format("Number of users who have completed less than %s completion: %s",
                        Constants.threshold, userBody.size()));

        // Final Check
        if (userBody.size() != 0) {
            LoggerSingleton.logger.error(String.format(
                    "FAILED - ALL the users who have done todos in cities %s have NOT completed %s percent of todos (There may be few who have)",
                    Arrays.toString(Constants.cities), Double.toString(Constants.threshold * 100)));
            Assert.assertTrue(false);
        }

        else {
            LoggerSingleton.logger.info(String.format(
                    "SUCCESS - ALL the users who have done todos in cities %s have completed %s percent of todos",
                    Constants.cities.toString(), Double.toString(Constants.threshold * 100)));
        }
    }
}
